version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: taskflow-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: taskflow_db
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    container_name: taskflow-app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://admin:1234@db:5432/taskflow_db
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres-data:
